### PR TITLE
prefer .ruby-version for rvm and rbenv now

### PR DESCRIPTION
**Pull request by Eric-Guo**

### CODE REVIEW

**Review by jonathanwiesel — CHANGES_REQUESTED** [review]
@Eric-Guo thanks for the contribution.

The file should be named `.ruby-version` in singular form, not `.ruby-versions` so the managers can recognise it.

(Please do not create a new commit for the fix, amend the existing one).

**Comment by Eric-Guo** [comment]
It's my typo, now correct 😄

**Review by jonathanwiesel — CHANGES_REQUESTED** [review]
@Eric-Guo the file is now `.ruby-verion` instead of `.ruby-version`

**Comment by Eric-Guo** [comment]
Oh... I'm 100% human now.. thanks...

**Pull request merged**
