### PR TITLE
Must given the height, otherwise in some case will lead stretch.

### PR DESCRIPTION
**Pull request by Eric-Guo**
To fix the problem show below:

screen shot 2016-09-21 at 3 18 46 pm

### CODE REVIEW

**Review by jonathanwiesel — COMMENTED** [review]
Hello @Eric-Guo, are you sure there isn't something forcing the image height and provoking the aspect break, maybe something in your stylesheet?

Could you please provide a testable code case of this beside a screenshot to evaluate the issue?

**Comment by Eric-Guo** [comment]
Yes, there is CSS set height for all img tag, to limit all the img in the paragraph, I can possible using `a.emoji` to having same effect, but I think given height at img is more good one if already given width, since emoji img expect to be square always.

**Comment by jonathanwiesel** [comment]
The `default_size` property was introduced to address cases when the use of stylesheets is not possible or troublesome (such as emails).

I'm afraid this is a problem with your stylesheet because when height is not specified the image will be square. You're stylesheet is forcing the image heights of all images, even emoji. I recommend you adjust the emoji sizes from the stylesheet itself instead of using the `default_size` global switch.

**Comment by Eric-Guo** [comment]
Understand, thanks.

**Pull request closed without merging**
