### PR TITLE
Restore the `emoji` asset directory, remove file type folders when installing the assets

### PR DESCRIPTION
**Pull request by stex**
References #30 

In the current version of the Gem, there are a few problems regarding Rails applications:

> **The asset files are missing an `emoji` directory.**

When loading the assets directly from the gem instead of installing them using the provided rake task, we'd have to add them to the list of assets to precompile using `*.svg` instead of `emoji/*.svg` as described in the README.

This could lead to the compilation of files we do not actually want to be compiled as they are not namespaced.

**Solution used in this PR:**  Added an `emoji` directory to the file type directories.

This is probably not the tidiest solution as it adds the same directory for all file types and an enclosing directory named `emoji` would have been nicer, but that would have involved changing the path generation itself.

> **Wrong image paths are generated for locally installed assets**

`rake gemojione:install_assets` copies all assets to `app/assets/images/emoji` by default. This means, that the folder structure will look like the following:
- `app/assets/images/emoji/svg/...`
- `app/assets/images/emoji/png/...`
- ...

The problem here is that `Gemojione#image_url_for_name` does not add the image type folder, so a generated image url would look something like this: `http://localhost:3000/assets/emoji/1F686.svg`

Both in `development` mode and when using precompiled assets, the missing directory will lead to images not being found.

**Solution used in this PR**: All assets are copied to the target directories root, e.g. to `app/assets/emoji`

Another solution would have been to alter `Gemojione#image_url_for_name` instead, adding the type directory based on `use_svg`

I added a test for the rake task to ensure that all files are actually copied. I haven't run it against travis yet so their might be a few things I'll have to adjust.

Update: The only test failing is jruby-head - and that's because the default gems could not be imported, leading to bundler not being available.

---

This PR will lead to the gem not being backwards-compatible as other users will most likely have adjusted their gem configuration to work around the above problems.

### CODE REVIEW

**Comment by jonathanwiesel** [comment]
@Stex great work, thanks for the contribution. 

I have one question though. 

I noticed than you first created an enclosing directory `/assets/emoji/` in c73c2dca06, but later changed it to a `emoji` directory per filetype (`assets/png/emoji/` and `assets/svg/emoji/`) in 6db901c48b because, as you mentioned, that involved changing the path generation.

I find the first solution more elegant and tidy, any drawbacks from changing the path generation?

**Comment by stex** [comment]
@jonathanwiesel I'd prefer the `emoji/svg/*.svg` solution, too. The reason I changed it to the current version was mainly to follow the current README.

What I'd like to do (and what would most likely need a major version release as it's most likely not backwards compatible) is the following:
- 1. Organize the assets in `assets/emoji/svg/`, `assets/emoji/png` and `assets/emoji/sprites`

**Edit**: Or even better, have them in `vendor/assets/...`. This way the asset pipeline already contains the path and we'll only have to add the files to the precompile-list
- 2. Combine `images_path` and `sprites_path`. `asset(s)_path` is already taken, so I'll use `gem_assets_path` as a placeholder here

Adding the correct assets to the precompilation list would then be done using the relative path within the assets directory - or we could provide an additional helper method:

``` ruby
config.assets.paths << Gemojione.gem_assets_path
# => "/path/to/gem/assets"

config.assets.precompile << 'emoji/svg/*.svg' 
# or
config.assets.precompile << Gemojione.asset_files(:svg)
```
- 3. Change `use_svg` to a more general `default_image_format` and add an image format parameter to the helper methods.

The only global switch would then be `use_sprites`, meaning that you can either always use `<span>` with a class name or various (well, two) image formats - or the sprite option could be added as an optional argument as well. As the gem only supports Ruby 2, keyword arguments might be a good solution here:

``` ruby
def self.image_url_for_name(name, format: self.default_image_format)
end

def self.image_tag_for_moji(moji, sprites: self.use_sprites, **options)
  if sprites
    ..
  else
    ... image_url_for_name(name, **options) ...
```

The additional argument would have to be added to all helper methods and be passed down to the corresponding base method (`image_url_for_name` resp. `image_tag_for_moji`). To keep this more or less simple, it would be sufficient to add `**options` to the outer methods and simply pass them on to the next method instead of having to specify all arguments everywhere.

**Comment by jonathanwiesel** [comment]
@Stex I agree that many changes need to be made in the the gem to make it more usable and follow better standards.  

> - 1. Organize the assets in `assets/emoji/svg/`, `assets/emoji/png` and `assets/emoji/sprites`
> 
> Edit: Or even better, have them in `vendor/assets/....` This way the asset pipeline already contains the path and we'll only have to add the files to the precompile-list

The `vendor/assets` way looks quite good actually, would be simpler to implement in my opinion.

> - 2. Combine `images_path` and `sprites_path`. `asset(s)_path` is already taken, so I'll use `gem_assets_path` as a placeholder here
> 
> Adding the correct assets to the precompilation list would then be done using the relative path within the assets directory - or we could provide an additional helper method

Agreed on the `gem_assets_path`. Following the decision for the first point, I think it would be simpler to just include the files instead of adding more helper methods.

> - 3. Change `use_svg` to a more general `default_image_format` and add an image format parameter to the helper methods.
> 
> The only global switch would then be use_sprites, meaning that you can either always use <span> with a class name or various (well, two) image formats

Agreed. This way it would be cleaner and tolerant for further image formats. 

> or the sprite option could be added as an optional argument as well. As the gem only supports Ruby 2, keyword arguments might be a good solution here
> 
> The additional argument would have to be added to all helper methods and be passed down to the corresponding base method (`image_url_for_name` resp. `image_tag_for_moji`). To keep this more or less simple, it would be sufficient to add `**options` to the outer methods and simply pass them on to the next method instead of having to specify all arguments everywhere.

What benefits or drawbacks you can identify on going this way over the previous one?

Thanks a lot for your effort

**Comment by jonathanwiesel** [comment]
@Stex any news on this?

**Comment by stex** [comment]
@jonathanwiesel Sorry, the last weeks were quite busy and I completely forgot about your question :/

> What benefits or drawbacks you can identify on going this way over the previous one?

Not exactly sure what you mean by "previous one". If I misunderstood you, please let me know.

If you meant the `default_image_format` setting: This would be an extension for it, allowing to use different image formats per use of e.g. `replace_named_moji_with_images`. You could set a global image format which would be the default value for the helper method, but you could change it to e.g. use `png` in emails and `svg` when rendering application templates.

Regarding the `**options`: The `replace_xxx_with_images` functions internally all call the `image_tag_for_moji` function. As this function is the only one that would actually do anything with the `image_format` option, I just thought it might be a good idea to not explicitly list it in each of them:

``` ruby
def self.image_tag_for_moji(moji, image_format: self.default_image_format)
  ...
end

def self.replace_named_moji_with_images(string, **options)
  ...
  Gemojione.image_tag_for_moji(moji, **options)
  ...
end
```

This way it's easy to add more options later without having to change any of the helper methods.
If there should be an option which applies directly to one of the helper method, it could be added as own keyword argument while leaving `**options`:

``` ruby
def self.replace_named_moji_with_images(string, new_option:, **options)
```

**Comment by jonathanwiesel** [comment]
@Stex no problem, we've all been there.

> Not exactly sure what you mean by "previous one". If I misunderstood you, please let me know.

Indeed, after reading it again now neither I understood that one 😅 , sorry for that. I agree with that solution, seems very clean, flexible and easier to maintain, you can proceed when you have the time.

Thanks for the effort.

**Comment by stex** [comment]
I'll close this pull request and start a new one.

Just to confirm: This will definitely not be backwards compatible with current installations and will therefore require a bump of the major version number.

**Comment by jonathanwiesel** [comment]
@Stex agreed

**Pull request closed without merging**
