### PR TITLE
Remove executable bit from images

### PR DESCRIPTION
**Pull request by balasankarc**
While packaging this gem for Debian, these executable bits on images caused errors. Also, images being executables doesn't seem right.

### CODE REVIEW

**Comment by jonathanwiesel** [comment]
Nice one @balasankarc, could you please remove the executable bit from all files that has it to merge the pull request (I believe there are 388).

**Comment by balasankarc** [comment]
@jonathanwiesel All files? Or all image files?

**Comment by jonathanwiesel** [comment]
@balasankarc all image files, sorry

**Comment by balasankarc** [comment]
@jonathanwiesel  Is there any remaining? `ls -l` on assets/images give me none.

**Comment by jonathanwiesel** [comment]
@balasankarc I used the following command surfing around and found 388 files with the "x" flag in the assets/images directory. Your commit seems to refers 300:

```
$ find . -maxdepth 1 -perm -111 -type f
```

**Comment by balasankarc** [comment]
Ok, I also saw that. But, when I tried it on my repo's HEAD (after applying this MR), I got 0. :)

**Comment by jonathanwiesel** [comment]
@balasankarc you're right, the "300" is a diff limit in the Github interface; however in the shell the diff show 388 changes and no "x" flags. 

Thanks

**Pull request merged**
