### PR TITLE
Unicode9

### LINKED ISSUE #10: Add Unicode 9 Emoji
Emoji One 2.2.4 was released the other day with the Unicode 9 emoji! Can we get an update with them? 

http://emojione.com/releases/#2.2.4

### PR DESCRIPTION
**Pull request by jonathanwiesel**
This introduces the new unicode 9 definitions and assets.
##### ~~Some side notes about this pull request:~~
- ~~The following definitions do not have a `moji` property (they are part of the unicode set but do not represent an emoji _per se_; yet image assets have been made so I decided to include them).~~

``` pre
asterisk_symbol
pound_symbol
digit_zero
digit_one
digit_two
digit_three
digit_four
digit_five
digit_six
digit_seven
digit_eight
digit_nine
```
- ~~New category `regional` has been added, having regional indicators, for example:~~

``` js
{
  "regional_indicator_a": {
    "unicode": "1F1E6",
    "unicode_alternates": [],
    "name": "regional indicator symbol letter a",
    "shortname": ":regional_indicator_a:",
    "category": "regional",
    "aliases": [],
    "aliases_ascii": [],
    "keywords": [],
    "moji": "🇦"
  }
}
```

This resolves #10.

**Edit**: 
Also a breaking change is introduced since a new `egg` definition is included, now corresponding to the unicode `1F95A`, former `egg` (`1F373`) definition has been renamed to `cooking`. This can also be seen in the source (Ranks/emojione#284)

### CODE REVIEW

**Comment by connorshea** [comment]
It looks like you should just drop support for Ruby 1.9

**Comment by connorshea** [comment]
Looks good to me, only question is: what is the `objects_symbols` category for?

**Comment by connorshea** [comment]
Also `travel_places` vs. `travel`?

Things listed as `people` that aren't:
- `athletic_shoe`
- `bikini`
- `boot`
- `briefcase`
- `dark_sunglasses`
- `dolls`
- `dress`
- `high_heel`
- `jeans`
- `closed_umbrella`
- `eyeglasses`
- `necktie`
- `mans_shoe`
- `kimono`
- `footprints`
- `handbag`
- `mortar_board`

Should I report these to EmojiOne?

**Comment by jonathanwiesel** [comment]
@connorshea 

> It looks like you should just drop support for Ruby 1.9

Yep, just noticed that `json` package was updated to v2.0.1 and now requires ruby >= v2.0. 
Will remove it from the `.travil.yml` and list it as a breaking change.

> Looks good to me, only question is: what is the `objects_symbols` category for?

It seems all `objects_symbols` definitions have been removed from EmojiOne in the latest release for some reason.

> Also `travel_places` vs. `travel`?

Like the previous, for some reason they removed this ones (`travel_places`) too.

> Things listed as `people` that aren't

It seems this is a problem in the source repo's definition file also. Will need to fix their categorization to bring it here.

Looks like most issues are related to the source repo. Will be better to clear it with them and work a fix according to what's their opinion. So yeah, if you don't mind, could you please report these to the source?

**Comment by connorshea** [comment]
@jonathanwiesel will do :)

**Comment by connorshea** [comment]
@jonathanwiesel would it be possible to add a toggle that would enable/disable the non-Unicode-official emoji? I really don't like the idea of moving away from the Unicode standard.

(Should I open an issue for that?)

**Comment by jonathanwiesel** [comment]
@connorshea which ones are you referring to?

**Comment by connorshea** [comment]
@jonathanwiesel oh I misunderstood what you meant by the lack of moji property, nevermind!

**Comment by jonathanwiesel** [comment]
> Things listed as people that aren't:
> 
> ```
> athletic_shoe
> bikini
> boot
> briefcase
> dark_sunglasses
> dolls
> dress
> high_heel
> jeans
> closed_umbrella
> eyeglasses
> necktie
> mans_shoe
> kimono
> footprints
> handbag
> mortar_board
> ```
> 
> Should I report these to EmojiOne?

@connorshea I just noticed that, even when it doesn't make much sense, if you look into emoji keyboards and [emojipedia](http://emojipedia.org/people/), you'll see that those emoji actually belong to the people category (Except for `dolls` that is correctly placed on the `objects` category, I imagine it was a mistake).

screen shot 2016-07-09 at 22 24 36

**Comment by jonathanwiesel** [comment]
@connorshea so I guess it's not an actual issue since the emoji standard indeed categorizes those emoji in the people category.

Still, I'll wait a while longer for an action on the extra categories EmojiOne seem to have added then removed again. If no anser comes around I think the better would be to remove them since they are not actually part of emoji keyboards. The same can apply to the regional category and those `digit...` mentioned in the initial comment of this PR

**Comment by jonathanwiesel** [comment]
Following what has been said in Ranks/emojione#299, definitions under `travel_places` and `objects_symbols` should not be included. Will remove.

Also, following emoji standardisation, will remove `regional` "emoji" since they aren't really emoji. Same goes for  `asterisk_symbol`, `pound_symbol` and `digit_...`.

**Comment by connorshea** [comment]
I wonder if there's any way to organize these in a similar way to iOS, since it makes a lot more sense when the people are all together and then the accessories/clothing are all together, even if everything is in the same overall category.

**Comment by connorshea** [comment]
Reminder to remove JRuby 1.9 btw

**Comment by jonathanwiesel** [comment]
> I wonder if there's any way to organize these in a similar way to iOS, since it makes a lot more sense when the people are all together and then the accessories/clothing are all together, even if everything is in the same overall category.

@connorshea Indeed I could implement the emoji `order` property for definitions, this is present in the source (never checked the order integrity however). Could be a great future feature.

**Comment by jonathanwiesel** [comment]
> Reminder to remove JRuby 1.9 btw

@connorshea thanks for the reminder. I forgot about JRuby.

**Pull request merged**
