### PR TITLE
Add SVG usage option

### PR DESCRIPTION
**Pull request by jonathanwiesel**
This introduces the option to use SVG assets instead of PNGs.

Will only need to set:

``` ruby
Gemojione.use_svg = true
```
##### Some side notes about this pull request:
- The `images_path` getter has been moved from `index.rb` to the main `gemojione.rb` module. So a **breaking change** is introduced because people serving assets directly from the gem will need to change in their rails app:

``` ruby
config.assets.paths << Gemojione.index.images_path

# to 

config.assets.paths << Gemojione.images_path
```
- Also note that if using `use_svg = true` then asset precompilation config must also be changed:

``` ruby
config.assets.precompile << "emoji/*.png" 

# to

config.assets.precompile << "emoji/*.svg" 
```
- The `install_assets` rake task now installs both asset types (PNGs and SVGs).

---
### To do
- [x] Move `png` assets to a new `assets/png` directory.
- [x] Add `svg` assets to a new `assets/svg` directory.
- [X] Rebase master when #18 gets merged

Will wait for #18 to be merged for easier rebasing and avoid assets disaster.

### CODE REVIEW

**Comment by jonathanwiesel** [comment]
@tsigo @connorshea I know the first side note affects applications such as Gitlab, do you see any inconvenient with this?

**Comment by rspeicher** [comment]
@jonathanwiesel Thanks for the heads-up! If you include a note in the changelog we'll remember to do it when we next update the gem.

**Comment by jonathanwiesel** [comment]
@tsigo sure thing 😉

**Comment by jonathanwiesel** [comment]
Latest commit actual action were:
- Remove the following definitions that aren't really part of the emoji definitive standard and have also been removed from the source:

```
bouquet2
finger_pointing_down
finger_pointing_down2
finger_pointing_left
finger_pointing_right
finger_pointing_up
hand_splayed_reverse
hand_victory
heart_tip
left_writing_hand
lips2
thumbs_down_reverse
thumbs_up_reverse
turned_ok_hand
```
- Move png assets to `assets/png`.
- Add svg assets to `assets/svg`.
- Fix image_path method.
- Fix readme.

**Comment by connorshea** [comment]
._. that's a lot of changed files

**Comment by jonathanwiesel** [comment]
@connorshea yeah, I had to move all existing PNGs to a new subdirectory, and add all new SVG assets.

Apart from removing some rogue definitions and finally fix the lib.

Shouldn't have done it on the same commit though

**Comment by jonathanwiesel** [comment]
Well I split the latest commit then force pushed the branch but for reason it doesn't seem to be updated.

**Comment by connorshea** [comment]
YOLO, as the kids say.

**Comment by jonathanwiesel** [comment]
It seem it has come back to it senses. It should be more readable now.

**Pull request merged**
